"""
Cross Validation Module
Uses Qwen2.5-7B to verify consistency of answers generated by 14B model.
Consistent → confidence=high, inconsistent → confidence=low (optional drop)
"""

import logging
from vllm import LLM, SamplingParams

from .prompts import build_verify_prompt

logger = logging.getLogger(__name__)


def simple_answer_match(a: str, b: str) -> bool:
    """
    Simple string matching:
    - Exact match
    - One contains the other (good for numeric answers)
    - Match after extracting numbers
    """
    a, b = a.strip().lower(), b.strip().lower()
    if a == b:
        return True
    if a in b or b in a:
        return True

    # Extract and compare numbers
    import re
    nums_a = re.findall(r"-?\d+\.?\d*", a)
    nums_b = re.findall(r"-?\d+\.?\d*", b)
    if nums_a and nums_b and nums_a[0] == nums_b[0]:
        return True

    return False


class CrossValidator:
    """
    Uses a lightweight verification model to double-check generated CoT entries.
    Only applicable for questions with standard answers or objectively verifiable (math, logic MCQs, etc.).
    Skips verification for open-ended questions, default confidence=medium.
    """

    VERIFIABLE_DOMAINS = {"math", "logic", "science"}

    def __init__(self, verifier_model: str = "Qwen/Qwen2.5-7B-Instruct"):
        logger.info(f"Loading verifier model: {verifier_model}")
        self.llm = LLM(
            model=verifier_model,
            tensor_parallel_size=1,
            gpu_memory_utilization=0.60,
            max_model_len=512,
        )
        self.sampling_params = SamplingParams(
            temperature=0.0,   # Greedy decoding for deterministic answers
            max_tokens=128,
            stop=["<|im_end|>", "\n\n"],
        )
        from transformers import AutoTokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(verifier_model)

    def validate_batch(
        self,
        entries: list[dict],
        drop_low_confidence: bool = False,
    ) -> list[dict]:
        """
        Validate a batch of entries.
        Returns list of entries with confidence field.
        When drop_low_confidence=True, filters out inconsistent entries.
        """
        # Separate verifiable / non-verifiable
        verifiable = [e for e in entries if e.get("domain") in self.VERIFIABLE_DOMAINS]
        non_verifiable = [e for e in entries if e.get("domain") not in self.VERIFIABLE_DOMAINS]

        # Mark non-verifiable as medium confidence
        for e in non_verifiable:
            e["confidence"] = "medium"

        # Batch verification
        if verifiable:
            prompts = [
                self._build_verify_prompt(e["question"])
                for e in verifiable
            ]
            outputs = self.llm.generate(prompts, self.sampling_params)

            for entry, output in zip(verifiable, outputs):
                verifier_answer = output.outputs[0].text.strip()
                match = simple_answer_match(entry["answer"], verifier_answer)
                entry["confidence"] = "high" if match else "low"
                entry["verifier_answer"] = verifier_answer

        all_entries = verifiable + non_verifiable

        if drop_low_confidence:
            before = len(all_entries)
            all_entries = [e for e in all_entries if e["confidence"] != "low"]
            dropped = before - len(all_entries)
            logger.info(f"Cross validation: Dropped {dropped} low-confidence entries")

        return all_entries

    def _build_verify_prompt(self, question: str) -> str:
        messages = [{"role": "user", "content": build_verify_prompt(question)}]
        return self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
